### PR TITLE
Improved command line for FFmpeg (fix bug on videos with chapters) and improved effect commands + Ability to create videos with only transition clips when sources are empty

### PR DESCRIPTION
**Pull request by DevanWolf**
The OG code uses unoptimized FFmpeg video generating code which is not recommended. These changes will get the job done making those thing faster than before.

### CODE REVIEW

**Comment by TeamPopplio** [comment]
Hi, thanks for contributing! I'll check this out when possible and upstream to the windows-xp and infinity branches if there's no issue.

**Comment by TeamPopplio** [comment]
Currently reviewing, I'll get back to you when I've surveyed it.

**Comment by TeamPopplio** [comment]
```C:\Users\DONT_\Desktop\ytp-windows\YTPPlusCLI\global.js:89
        var args =" -i \"" + `${video.replace(/\\/g,"\\\\").replace(/\//g,(process.platform === "win32" ? "\\\\" : "/"))} + "\" -pix_fmt yuv420p -vf scale="+resolution[0]+"x"+resolution[1]+",setsar=1:1,fps=fps="+fps + " -ar 44100 -ac 2 -map_metadata -1 -map_chapters -1 -y \"" + output + ".mp4\"";
                              ^

SyntaxError: Unexpected identifier
←[90m    at wrapSafe (node:internal/modules/cjs/loader:1024:16)←[39m
←[90m    at Module._compile (node:internal/modules/cjs/loader:1072:27)←[39m
←[90m    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)←[39m
←[90m    at Module.load (node:internal/modules/cjs/loader:973:32)←[39m
←[90m    at Function.Module._load (node:internal/modules/cjs/loader:813:14)←[39m
←[90m    at Module.require (node:internal/modules/cjs/loader:997:19)←[39m
←[90m    at require (node:internal/modules/cjs/helpers:92:18)←[39m
    at Object.<anonymous> (C:\Users\DONT_\Desktop\ytp-windows\YTPPlusCLI\prompts.js:4:12)
←[90m    at Module._compile (node:internal/modules/cjs/loader:1108:14)←[39m
←[90m    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)←[39m```
Currently nonfunctional, please re-open when fully tested.

**Comment by DevanWolf** [comment]
Okay, corrected. Let's try this again.

**Comment by TeamPopplio** [comment]
```
STARTING EFFECT ON CLIP 13 EFFECT randomsoundmute.js
ffmpeg version N-100201-gb51b9bbd42-sherpya Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 10-win32 (GCC) 20201125
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'c:\Users\DONT_\Desktop\ytp-windows\YTPPlusCLI/shared/temp/temp.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.64.100
  Duration: 00:00:04.60, start: 0.000000, bitrate: 572 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, smpte170m/smpte170m/bt709), 640x480 [SAR 1:1 )
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 130 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
Invalid input file index: 1.

An error has occured.
```
still getting issues, not sure where this one originates

**Comment by TeamPopplio** [comment]
(from discord) plugin testing with randomsoundmute.js causes this... weird error?
```
STARTING EFFECT ON CLIP 0 EFFECT randomsoundmute.js
ffmpeg version N-100201-gb51b9bbd42-sherpya Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 10-win32 (GCC) 20201125
c:\Users\DONT_\Desktop\ytp-windows\YTPPlusCLI: Permission denied

An error has occured.

Error: Command failed: "C:\Users\DONT_\Desktop\ytp-windows\YTPPlusCLI\node_modules\ffmpeg-cli\ffmpeg\ffmpeg.exe"  -i "c"
ffmpeg version N-100201-gb51b9bbd42-sherpya Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 10-win32 (GCC) 20201125
c:\Users\DONT_\Desktop\ytp-windows\YTPPlusCLI: Permission denied```

**Comment by TeamPopplio** [comment]
Works now

**Pull request merged**
